# Generated by Django 5.2 on 2025-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('local_path', models.FileField(upload_to='videos/')),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
